### ISSUE TITLE
Path error in test, I think due to my using a windows machine. Should be fixable by using `os.path.join` in `COMP_FILE` under `TestModify`. Though you may want to consider using `pathlib` throughout for a more convenient long term handling of file paths than `os`.

### ISSUE THREAD

**Issue by crvernon** [IMMM-SFA/statemodify#43]

**Comment by ekblad** [comment]
following up on this. `pathlib` is cleaner, integrated with adjacent libraries (see [here](https://github.com/pydata/xarray/pull/1514)), and can be used in place of `os` for any functions taking files or directories/generators as input. +1 for @barneydobson's suggestion.
