### ISSUE TITLE
I don't think you have to go too far in this, as it is probably not the responsibility of  to fully train a user in StateMod, but since I think there is an implication that  is a portal to new users of StateMod, a little more help explaining its principles in the notebooks would be appreciated. I understand you are all probably experts in it so it is probably difficulty to identify what is implicit and what is not, so I will just list things I would appreciate explaining under this task as I identify them

### ISSUE THREAD

**Issue by crvernon** [IMMM-SFA/statemodify#48]

**Comment by crvernon** [comment]
From the original issue:

I see there is a river_id and structure_id in the model output file, which are the same. It seems these are the same as users? But maybe this is also the same as reservoirs? Are these four things always the same?

Maybe whenever you first mention a StateMod file type (e.g., .ddr) you could link to a description of that file type - though I can see that the description on their readthedocs is limited and when I go further in it just gets more complicated rather than clearer.. If you know where to find a good description probably link that otherwise those 'NOTE' blue boxes you have been using would be good.

**Comment by rg727** [comment]
In regards to the first comment: `river_id` and `structure_id` are the same, but this is not the same as reservoirs. We create functionality to preserve the whole output file in the `.parquet` file, but only utilize the "shortage" column. Much of the detail in the results file, especially for columns that aren't being used, is best left out of the notebook. However, we have gone through the notebooks and linked to the StateMod documentation for each StateMod file that is mentioned if the user wants to read more about the input and output file structures.
