### ISSUE TITLE
functionality:  modify ddm 

### ISSUE THREAD

**Issue by crvernon** [IMMM-SFA/statemodify#5]
**Task**:

Ensure the `modify_ddm` function:

- [x] produces the desired result
- [x] will run successfully with each of the five `StateMod` basins

**Code sample**:
```python
import statemodify as stm

# a dictionary to describe what you want to modify and the bounds for the LHS
setup_dict = {
    "names": ["municipal", "standard"],
    "ids": [["7200764", "7200813CH"], ["7200764_I", "7200818"]],
    "bounds": [[-1.0, 1.0], [-1.0, 1.0]]
}

output_directory = "<your desired output directory>"
scenario = "<your scenario name>"

# the number of samples you wish to generate
n_samples = 4

# seed value for reproducibility if so desired
seed_value = None

# my template file.  If none passed into the `modify_ddm` function, the default file will be used.
template_file = "<your ddm template file>"

# the field that you want to use to query and modify the data
query_field = "id"

# generate a batch of files using generated LHS
stm.modify_ddm(modify_dict=setup_dict,
               output_dir=output_directory,
               scenario=scenario,
               n_samples=n_samples,
               seed_value=seed_value,
               query_field=query_field,
               template_file=template_file)
```

**Comment by rg727** [comment]
Working on testing these and there is one small issue. For some parameterizations, we get some negative values which causes StateMod to fail. I think negatives might be ok for StateMod, it's just that there are too many decimals that are running into other columns. A second fix would be to ask the question if "negatives really make sense here". Negative demand means that the user is transferring water to another place. I don't think this makes sense unless the user is an interbasin transfer. However, Chris, maybe if you just truncate the decimals first, I can rerun and see what happens. 
)
![Capture](https://user-images.githubusercontent.com/31748312/211174378-523b1497-fbcd-4472-b513-2b3623018eb3.PNG)

**Comment by rg727** [comment]
One other thing to just note here Chris, is that the bounds on the multipliers should be between 0.5 and 1.5. So we're sampling the demands going anywhere between 1/2 of historical to 1.5 times greater than historical. Thanks!

**Comment by rg727** [comment]
IT WORKS FOR ALL THE BASINS!!

![Alt Text](https://media.giphy.com/media/PAbvWdphmfRhULRHHD/giphy.gif)
